base_100 = "#FFFFFF"
base_200 = "#ECECEC"
base_300 = "#DBDBDB"
base_content = "#262633"
primary = "#2563EB"
primary_content = "#FFFFFF"
secondary = "#5B5F8C"
secondary_content = "#FFFFFF"
accent = "#2DD4BF"
accent_content = "#FFFFFF"
neutral = "#000000"
neutral_content = "#FFFFFF"
info = "#3B82F6"
info_content = "#FFFFFF"
success = "#22C55E"
success_content = "#FFFFFF"
warning = "#FACC15"
warning_content = "#000000"
error = "#DC2626"
error_content = "#000000"
