
[env]
RUST_LOG="morphiq_lume=debug"

# SERVICE_DB_URL="postgres://akaza:Dev_only.2025@localhost/morphiq_lume_db"
# SERVICE_DEV_DB_URL="postgres://postgres:P0stgres.2025@localhost/morphiq_lume_db"

SERVICE_DB_URL="postgres://castlebyte_dev:Dev_only.2025@localhost/morphiq_lume_db"
SERVICE_DEV_DB_URL="postgres://postgres:Postgres.2025@localhost/morphiq_lume_db"
