use iced::{widget::Text, Theme};

use crate::gui::styles::style_constant::ICONS;

pub enum Icon {
    Cancel,
    UserTimes,
    UserPlus,
    Users,
    User,
    Calendar,
    Search,
    Logout,
    Clipboard,
    Cog,
    CogAlt,
    UpOpen,
    RightOpen,
    LeftOpen,
    DownOpen,
    Plus,
    ThLarge,
    SortAltDown,
    SortAltUp,
    Language,
    Language1,
    GithubCircledAlt2,
    PaperPlane,
    Link,
    Export,
    DownloadAlt,
    Equalizer,
    Download,
    Bookmark,
    Mobile,
    Tag,
    Tags,
    MailAlt,
    Dot3,
    Eye,
    EyeOff,
    Export1,
    Chart,
    Spin3,
    Spin6,
    Chrome,
    CommentInvAlt2,
    ChartBar,
    ChartPie,
    SunInv,
    MoonInv,
    VolumeUp,
    Wrench,
    FilePdf,
    DocTextInv,
}

impl Icon {
    pub fn codepoint(&self) -> char {
        match self {
            Icon::Cancel => 'a',
            Icon::UserTimes => 'b',
            Icon::UserPlus => 'c',
            Icon::Users => 'd',
            Icon::User => 'e',
            Icon::Calendar => 'f',
            Icon::Search => 'g',
            Icon::Logout => 'h',
            Icon::Clipboard => 'i',
            Icon::Cog => 'j',
            Icon::CogAlt => 'k',
            Icon::UpOpen => 'l',
            Icon::RightOpen => 'm',
            Icon::LeftOpen => 'n',
            Icon::DownOpen => 'o',
            Icon::Plus => 'p',
            Icon::ThLarge => 'q',
            Icon::SortAltDown => 'r',
            Icon::SortAltUp => 's',
            Icon::Language => 't',
            Icon::Language1 => 'u',
            Icon::GithubCircledAlt2 => 'v',
            Icon::PaperPlane => 'w',
            Icon::Link => 'x',
            Icon::Export => 'y',
            Icon::DownloadAlt => 'z',
            Icon::Equalizer => '1',
            Icon::Download => '2',
            Icon::Bookmark => '3',
            Icon::Mobile => '4',
            Icon::Tag => '5',
            Icon::Tags => '6',
            Icon::MailAlt => '7',
            Icon::Dot3 => '8',
            Icon::Eye => '9',
            Icon::EyeOff => '0',
            Icon::Export1 => 'A',
            Icon::Chart => 'B',
            Icon::Spin3 => 'C',
            Icon::Spin6 => 'D',
            Icon::Chrome => 'E',
            Icon::CommentInvAlt2 => 'F',
            Icon::ChartBar => 'G',
            Icon::ChartPie => 'H',
            Icon::SunInv => 'I',
            Icon::MoonInv => 'J',
            Icon::VolumeUp => 'K',
            Icon::Wrench => 'L',
            Icon::FilePdf => 'M',
            Icon::DocTextInv => 'N',
        }
    }

    pub fn to_text<'a>(&self) -> Text<'a, Theme> {
        Text::new(self.codepoint().to_string()).font(ICONS)
    }
}
